### ISSUE TITLE
How can I solve "RuntimeError:"?

### ISSUE THREAD

**Issue by TatsuhiroAbe** [ysn2233/attentioned-dual-stage-stock-prediction#1]
When I ran the code in test phase, I got this error

> Traceback (most recent call last):
  File "trainer.py", line 152, in <module>
    trainer.test(mname, batch_size)
  File "trainer.py", line 66, in test
    y_pred_train = self.predict(x_train, y_train, y_seq_train, batch_size)
  File "trainer.py", line 90, in predict
    y_res = self.decoder(code, var_y_input)
  File "/home/tatsuhiro/PycharmProjects/untitled/venv/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tatsuhiro/PycharmProjects/untitled/attentioned-dual-stage-stock-prediction-master/model.py", line 101, in forward
    ct = torch.bmm(beta_t.unsqueeze(1), h)
RuntimeError: invalid argument 6: wrong matrix size at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:477

I do not change any of programs.
How can I solve this problem?

**Comment by cubicgate** [comment]
Hi @TatsuhiroAbe , How did you solve this problem?  Thanks!

**Comment by cubicgate** [comment]
Hi @ysn2233  , How to solve this problem? Thanks!
